export const initialData = {
  date: null,
  shift1: {
    priceMS: 0.0,
    priceHSD: 0.0,
    machine1: {
      openingBalanceHSD: 0.0,
      closingBalanceHSD: 0.0,
      openingBalanceMS: 0.0,
      closingBalanceMS: 0.0,
      tankerMS: 0.0,
      tankerHSD: 0.0,
      totalSaleMS: 0.0,
      totalSaleHSD: 0.0,
      totalPriceHSD: 0.0,
      totalPriceMS: 0.0,
      listPaytm: [],
      listBorrowings: [],
      listSpendings: [],
      listDeposits: [],
      totalPaytm: 0.0,
      totalBorrowings: 0.0,
      totalSpendings: 0.0,
      totalDeposits: 0.0,
      totalDue: 0.0,
    },
    machine2: {
      openingBalanceHSD: 0.0,
      closingBalanceHSD: 0.0,
      openingBalanceMS: 0.0,
      closingBalanceMS: 0.0,
      tankerMS: 0.0,
      tankerHSD: 0.0,
      totalSaleMS: 0.0,
      totalSaleHSD: 0.0,
      totalPriceHSD: 0.0,
      totalPriceMS: 0.0,
      listPaytm: [],
      listBorrowings: [],
      listSpendings: [],
      listDeposits: [],
      totalPaytm: 0,
      totalBorrowings: 0,
      totalSpendings: 0,
      totalDeposits: 0,
      totalDue: 0.0,
    },
  },
  shift2: {
    priceHSD: 0.0,
    priceMS: 0.0,
    machine1: {
      openingBalanceHSD: 0.0,
      closingBalanceHSD: 0.0,
      openingBalanceMS: 0.0,
      closingBalanceMS: 0.0,
      tankerMS: 0.0,
      tankerHSD: 0.0,
      totalSaleMS: 0.0,
      totalSaleHSD: 0.0,
      totalPriceHSD: 0.0,
      totalPriceMS: 0.0,
      listPaytm: [],
      listBorrowings: [],
      listSpendings: [],
      listDeposits: [],
      totalPaytm: 0,
      totalBorrowings: 0,
      totalSpendings: 0,
      totalDeposits: 0,
      totalDue: 0.0,
    },
    machine2: {
      openingBalanceHSD: 0.0,
      closingBalanceHSD: 0.0,
      openingBalanceMS: 0.0,
      closingBalanceMS: 0.0,
      tankerMS: 0.0,
      tankerHSD: 0.0,
      totalSaleMS: 0.0,
      totalSaleHSD: 0.0,
      totalPriceHSD: 0.0,
      totalPriceMS: 0.0,
      listPaytm: [],
      listBorrowings: [],
      listSpendings: [],
      listDeposits: [],
      totalPaytm: 0,
      totalBorrowings: 0,
      totalSpendings: 0,
      totalDeposits: 0,
      totalDue: 0.0,
    },
  },
};

export const urlDev = "http://localhost:1333";
export const urlProd = "https://arihantfillingstationbackend.onrender.com";
